SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PostcodeQueries](
	[Id] [uniqueidentifier] NOT NULL,
	[Postcode] [varchar](8) NULL,
	[QueryDate] [datetime] NOT NULL,
	[Deliverable] [bit] NOT NULL,
 CONSTRAINT [PK_PostcodeQueries] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO