SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PostcodeContacts](
	[Id] [uniqueidentifier] NOT NULL,
	[Postcode] [varchar](8) NOT NULL,
	[Email] [varchar](250) NOT NULL,
	[DateAdded] [datetime] NOT NULL,
	[IsDeliverable] [BIT] NOT NULL
 CONSTRAINT [PK_PostcodeContacts] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

