SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DiscountCodes](
	[Id] [UNIQUEIDENTIFIER] NOT NULL,
	[DiscountId] [UNIQUEIDENTIFIER] NOT NULL,
	[Code] [NVARCHAR](50) NOT NULL,
	[Description] [NVARCHAR](250) NULL,
	[IsInactive] [BIT] NOT NULL DEFAULT 0
 CONSTRAINT [PK_DiscountCode] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Code] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[DiscountCodes]  WITH CHECK ADD  CONSTRAINT [FK_DiscountCodes_Discounts] FOREIGN KEY([DiscountId])
REFERENCES [dbo].[Discounts] ([Id])
GO

ALTER TABLE [dbo].[DiscountCodes] CHECK CONSTRAINT [FK_DiscountCodes_Discounts]
GO

IF EXISTS
(
    SELECT *
    FROM [sys].[columns]
    WHERE [object_id] = OBJECT_ID(N'[dbo].[Discounts]')
          AND [name] = 'Code'
)

ALTER TABLE [dbo].[Discounts] DROP COLUMN Code
GO